{"name": "test_user_login_wrong", "status": "broken", "statusDetails": {"message": "_pytest.fixtures.FixtureLookupError: ('api', <FixtureRequest for <Function test_user_login_wrong>>)", "trace": "file C:\\Users\\Administrator\\PycharmProjects\\pytest\\testcase\\test_login.py, line 19\n      @allure.testcase(\"/basic/auth/login\")\n      @allure.story(\"测试登录密码错误\")  # 功能块，具有相同feature或story的用例将规整到相同模块下,执行时可用于筛选\n      # 登录失败，用户账户错误\n      def test_user_login_wrong(self,api):\nE       fixture 'api' not found\n>       available fixtures: addoption_env, cache, capfd, capfdbinary, caplog, capsys, capsysbinary, case_data, do_login, doctest_namespace, env, get_excel, get_token_class, monkeypatch, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory\n>       use 'pytest --fixtures [testpath]' for help on them.\n\nC:\\Users\\Administrator\\PycharmProjects\\pytest\\testcase\\test_login.py:19"}, "start": 1600237676108, "stop": 1600237676109, "uuid": "ff0908e5-9622-4f4d-a220-20d14e878dde", "historyId": "8923e36b93bfcbf2b1b29bba9c76fef6", "testCaseId": "4b6bcd6bc9f4b93fe085c2939884ea45", "fullName": "testcase.test_login.TestLogin#test_user_login_wrong", "labels": [{"name": "severity", "value": "critical"}, {"name": "feature", "value": "测试登录模块"}, {"name": "story", "value": "测试登录密码错误"}, {"name": "parentSuite", "value": "testcase"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "TX5C3S1L7D31UYD"}, {"name": "thread", "value": "16656-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.test_login"}], "links": [{"type": "test_case", "url": "/basic/auth/login", "name": "/basic/auth/login"}]}